- name: Setup DMZ server for WordPress and EC-Cube
  hosts: dmz
  become: yes

  tasks:
    - name: Install required packages
      yum:
        name:
          - epel-release
          - nginx
          - mariadb-server
          - python3
          - python3-PyMySQL  # MySQLモジュールを追加
          - php
          - php-fpm
          - php-mysqlnd
          - php-gd
        state: present

    - name: Start and enable nginx and mariadb
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - nginx
        - mariadb
