- name: Setup DMZ server for WordPress and EC-Cube
  hosts: dmz
  become: yes

  vars:
    mariadb_root_password: "Hard-ing0"

  tasks:
    # 必要なパッケージのインストール
    - name: Install required packages
      yum:
        name:
          - epel-release
          - nginx
          - mariadb-server
          - python3
          - python3-PyMySQL  # MySQLモジュールを追加
          - php
          - php-fpm
          - php-mysqlnd
          - php-gd
        state: present

    # ファイアウォールの無効化
    - name: Stop and disable firewalld for unrestricted access
      service:
        name: firewalld
        state: stopped
        enabled: no

    # NginxとMariaDBの起動と有効化
    - name: Start and enable nginx and mariadb
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - nginx
        - mariadb

    # MariaDB rootユーザの認証プラグインを変更し、パスワードを設定
    - name: Change root authentication plugin to mysql_native_password
      mysql_user:
        name: root
        host: localhost
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        plugin: mysql_native_password
        priv: '*.*:ALL,GRANT'
        state: present

    # WordPressとEC-Cube用のデータベースを作成
    - name: Create databases for WordPress and EC-Cube
      mysql_db:
        name: "{{ item }}"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"
      loop:
        - wordpress_db
        - eccube_db

    # MariaDBのユーザと権限の設定
    - name: Configure MariaDB for WordPress and EC-Cube
      mysql_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        priv: "{{ item.db }}.*:ALL"
        host: localhost
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        state: present
      loop:
        - { name: 'admin', password: 'Hard-ing0', db: 'wordpress_db' }
        - { name: 'admin', password: 'Hard-ing0000', db: 'eccube_db' }
      notify:
        - Restart mariadb

  handlers:
    - name: Restart mariadb
      service:
        name: mariadb
        state: restarted
