- name: Setup DMZ server for WordPress and EC-Cube
  hosts: dmz
  become: yes

  vars:
    mariadb_root_password: "Hard-ing0"
    user_password: "Hard-ing0"
    users:
      - user01
      - user02
      - user03
      - user04
      - user05
      - user06
      - user07
      - user08
      - user09
      - user10
    eccube_version: "4.2.3"

  tasks:
    # 0. タイムゾーンの設定
    - name: Set timezone to Asia/Tokyo
      command: timedatectl set-timezone Asia/Tokyo

    # 1. ユーザーの追加
    - name: Create users with default skel
      user:
        name: "{{ item }}"
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
        create_home: yes
        shell: /bin/bash
      loop: "{{ users }}"

    - name: Add users to sudo group
      user:
        name: "{{ item }}"
        groups: wheel
        append: yes
      loop: "{{ users }}"

    # 2. 必要なパッケージのインストール
    - name: Install required packages
      yum:
        name:
          - epel-release
          - nginx
          - mariadb-server
          - python3
          - python3-PyMySQL
          - php
          - php-fpm
          - php-mysqlnd
          - php-gd
          - unzip
          - tar
        state: present

    # 3. 追加のPHPモジュールのインストール
    - name: Install additional PHP modules
      yum:
        name:
          - php-mbstring
          - php-xml
          - php-pdo
          - php-intl
          - php-opcache
          - php-zip
          - php-json
          - php-curl
        state: present

    # 4. ファイアウォールの無効化
    - name: Stop and disable firewalld for unrestricted access
      service:
        name: firewalld
        state: stopped
        enabled: no

    # 5. サービスの起動と有効化
    - name: Start and enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - mariadb
        - php-fpm

    # 6. MariaDBの設定
    - name: Change root authentication plugin to mysql_native_password
      mysql_user:
        name: root
        host: localhost
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        plugin: mysql_native_password
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Create databases for WordPress and EC-Cube
      mysql_db:
        name: "{{ item }}"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"
      loop:
        - wordpress_db
        - eccube_db

    - name: Configure MariaDB users
      mysql_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        priv: "{{ item.db }}.*:ALL"
        host: localhost
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        state: present
      loop:
        - { name: 'admin', password: 'Hard-ing0', db: 'wordpress_db' }
        - { name: 'admin', password: 'Hard-ing0000', db: 'eccube_db' }

    # 7. WordPressのインストールと設定
    - name: Download WordPress
      get_url:
        url: https://ja.wordpress.org/latest-ja.tar.gz
        dest: /tmp/latest-ja.tar.gz
        force: no

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest-ja.tar.gz
        dest: /var/www/html/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set permissions for WordPress
      file:
        path: /var/www/html/
        owner: nginx
        group: nginx
        recurse: yes

    # 8. EC-Cubeのインストールと設定
    - name: Create directory for EC-Cube
      file:
        path: /var/www/html/shop
        state: directory
        owner: nginx
        group: nginx

    - name: Download EC-CUBE
      get_url:
        url: "https://downloads.ec-cube.net/src/eccube-{{ eccube_version }}.tar.gz"
        dest: /tmp/eccube.tar.gz
        force: no

    - name: Extract EC-CUBE
      unarchive:
        src: /tmp/eccube.tar.gz
        dest: /var/www/html/shop/
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set permissions for EC-CUBE
      file:
        path: /var/www/html/shop/
        owner: nginx
        group: nginx
        recurse: yes

    # 9. Nginxの設定
    - name: Configure Nginx for WordPress and EC-Cube
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart nginx

    # 10. PHP-FPMの設定
    - name: Ensure PHP-FPM is running
      service:
        name: php-fpm
        state: started
        enabled: yes

    # 11. SELinuxの設定（必要に応じて）
    - name: Set SELinux context for /var/www/html
      sefcontext:
        target: '/var/www/html(/.*)?'
        setype: httpd_sys_content_t

    - name: Apply SELinux file context
      command: restorecon -Rv /var/www/html

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Restart mariadb
      service:
        name: mariadb
        state: restarted
