---
# tasks file for account_setup

- name: Create users with default skel
  user:
    name: "{{ item }}"
    password: "{{ user_password | password_hash('sha512') }}"
    state: present
    create_home: yes
    shell: /bin/bash
  loop: "{{ users }}"

- name: Add users to sudo group
  user:
    name: "{{ item }}"
    groups: wheel
    append: yes
  loop: "{{ users }}"
