packages:
  - epel-release
  - nginx
  - mariadb-server
  - python3
  - python3-PyMySQL
  - php
  - php-fpm
  - php-mysqlnd
  - php-gd
  - unzip
  - tar
  - curl
  - php-cli
  - php-mbstring
  - php-xml
  # EC-CUBE に必要な PHP モジュールを追加
  - php-intl
  - php-opcache
  - php-pdo
  - php-pdo_mysql
  - php-zip
