---
# tasks file for middleware_install

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present

- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - mariadb
    - php-fpm
